package com.yzx.yzxlocalstore.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yzx.yzxlocalstore.entity.GoodsType;
import com.yzx.yzxlocalstore.entity.TypeBean;
import com.yzx.yzxlocalstore.entity.User;
import com.yzx.yzxlocalstore.entity.GoodsInfo;

import com.yzx.yzxlocalstore.greendao.GoodsTypeDao;
import com.yzx.yzxlocalstore.greendao.TypeBeanDao;
import com.yzx.yzxlocalstore.greendao.UserDao;
import com.yzx.yzxlocalstore.greendao.GoodsInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsTypeDaoConfig;
    private final DaoConfig typeBeanDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig goodsInfoDaoConfig;

    private final GoodsTypeDao goodsTypeDao;
    private final TypeBeanDao typeBeanDao;
    private final UserDao userDao;
    private final GoodsInfoDao goodsInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsTypeDaoConfig = daoConfigMap.get(GoodsTypeDao.class).clone();
        goodsTypeDaoConfig.initIdentityScope(type);

        typeBeanDaoConfig = daoConfigMap.get(TypeBeanDao.class).clone();
        typeBeanDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        goodsInfoDaoConfig = daoConfigMap.get(GoodsInfoDao.class).clone();
        goodsInfoDaoConfig.initIdentityScope(type);

        goodsTypeDao = new GoodsTypeDao(goodsTypeDaoConfig, this);
        typeBeanDao = new TypeBeanDao(typeBeanDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        goodsInfoDao = new GoodsInfoDao(goodsInfoDaoConfig, this);

        registerDao(GoodsType.class, goodsTypeDao);
        registerDao(TypeBean.class, typeBeanDao);
        registerDao(User.class, userDao);
        registerDao(GoodsInfo.class, goodsInfoDao);
    }
    
    public void clear() {
        goodsTypeDaoConfig.clearIdentityScope();
        typeBeanDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        goodsInfoDaoConfig.clearIdentityScope();
    }

    public GoodsTypeDao getGoodsTypeDao() {
        return goodsTypeDao;
    }

    public TypeBeanDao getTypeBeanDao() {
        return typeBeanDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public GoodsInfoDao getGoodsInfoDao() {
        return goodsInfoDao;
    }

}
