package com.yzx.yzxlocalstore.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.yzx.yzxlocalstore.entity.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Number = new Property(1, String.class, "number", false, "NUMBER");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Phone = new Property(3, String.class, "phone", false, "PHONE");
        public final static Property Level = new Property(4, int.class, "level", false, "LEVEL");
        public final static Property Status = new Property(5, boolean.class, "status", false, "STATUS");
        public final static Property SalesCommission = new Property(6, double.class, "salesCommission", false, "SALES_COMMISSION");
        public final static Property IsShowBuyingPrice = new Property(7, boolean.class, "isShowBuyingPrice", false, "IS_SHOW_BUYING_PRICE");
        public final static Property IsShowBuyingProfit = new Property(8, boolean.class, "isShowBuyingProfit", false, "IS_SHOW_BUYING_PROFIT");
        public final static Property IsShowBuyingStore = new Property(9, boolean.class, "isShowBuyingStore", false, "IS_SHOW_BUYING_STORE");
        public final static Property Pwd = new Property(10, String.class, "pwd", false, "PWD");
    }


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NUMBER\" TEXT UNIQUE ," + // 1: number
                "\"NAME\" TEXT," + // 2: name
                "\"PHONE\" TEXT," + // 3: phone
                "\"LEVEL\" INTEGER NOT NULL ," + // 4: level
                "\"STATUS\" INTEGER NOT NULL ," + // 5: status
                "\"SALES_COMMISSION\" REAL NOT NULL ," + // 6: salesCommission
                "\"IS_SHOW_BUYING_PRICE\" INTEGER NOT NULL ," + // 7: isShowBuyingPrice
                "\"IS_SHOW_BUYING_PROFIT\" INTEGER NOT NULL ," + // 8: isShowBuyingProfit
                "\"IS_SHOW_BUYING_STORE\" INTEGER NOT NULL ," + // 9: isShowBuyingStore
                "\"PWD\" TEXT);"); // 10: pwd
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String number = entity.getNumber();
        if (number != null) {
            stmt.bindString(2, number);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(4, phone);
        }
        stmt.bindLong(5, entity.getLevel());
        stmt.bindLong(6, entity.getStatus() ? 1L: 0L);
        stmt.bindDouble(7, entity.getSalesCommission());
        stmt.bindLong(8, entity.getIsShowBuyingPrice() ? 1L: 0L);
        stmt.bindLong(9, entity.getIsShowBuyingProfit() ? 1L: 0L);
        stmt.bindLong(10, entity.getIsShowBuyingStore() ? 1L: 0L);
 
        String pwd = entity.getPwd();
        if (pwd != null) {
            stmt.bindString(11, pwd);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String number = entity.getNumber();
        if (number != null) {
            stmt.bindString(2, number);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(4, phone);
        }
        stmt.bindLong(5, entity.getLevel());
        stmt.bindLong(6, entity.getStatus() ? 1L: 0L);
        stmt.bindDouble(7, entity.getSalesCommission());
        stmt.bindLong(8, entity.getIsShowBuyingPrice() ? 1L: 0L);
        stmt.bindLong(9, entity.getIsShowBuyingProfit() ? 1L: 0L);
        stmt.bindLong(10, entity.getIsShowBuyingStore() ? 1L: 0L);
 
        String pwd = entity.getPwd();
        if (pwd != null) {
            stmt.bindString(11, pwd);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // number
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // phone
            cursor.getInt(offset + 4), // level
            cursor.getShort(offset + 5) != 0, // status
            cursor.getDouble(offset + 6), // salesCommission
            cursor.getShort(offset + 7) != 0, // isShowBuyingPrice
            cursor.getShort(offset + 8) != 0, // isShowBuyingProfit
            cursor.getShort(offset + 9) != 0, // isShowBuyingStore
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // pwd
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNumber(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPhone(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLevel(cursor.getInt(offset + 4));
        entity.setStatus(cursor.getShort(offset + 5) != 0);
        entity.setSalesCommission(cursor.getDouble(offset + 6));
        entity.setIsShowBuyingPrice(cursor.getShort(offset + 7) != 0);
        entity.setIsShowBuyingProfit(cursor.getShort(offset + 8) != 0);
        entity.setIsShowBuyingStore(cursor.getShort(offset + 9) != 0);
        entity.setPwd(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
